---
title: "Camps Bay High-frequency Sampling"
author: "Francois van Schalkwyk"
date: "2025-03-19"
output: html_document
---

# Workspace Set-Up

Make sure that you are working in the outfalls project, found in the working directory.

## Set working directory for all code chunks to project root directory

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

## Load required packages

```{r message = FALSE}
library(tidyverse)
library(dbplyr)
library(DBI)
library(pdftools)
library(readxl)
```

## Database Connection

```{r db connection}
# Enter credentials when prompted
con <- dbConnect(RPostgres::Postgres(),
  host = "aws-0-eu-central-1.pooler.supabase.com",
  port = 5432,
  user = str_c(rstudioapi::askForPassword(prompt = "Username: "), "wnrvdvesovnkmqbhkhjz", sep = "."),
  password = rstudioapi::askForPassword(),
  dbname = "postgres"
)
```

```{r}
dbGetInfo(con)
```

# Create sample set

```{r}
# Sites
site <- tibble(site_id = c("CN10", "CN11", "CN41", "CN31"))

# Dates
date <- tibble(date = seq(ymd("2025-05-19"), ymd("2025-05-30"), "1 day")) |>
  mutate(day = wday(date, week_start = "Monday")) |>
  filter(!(day %in% c(6, 7))) |>
  select(-day)

# Hours
hour <- tibble(hour = seq(8, 17, 1))

# Cross join
labels <- site |>
  cross_join(date) |>
  cross_join(hour) |>
  arrange(site_id, date, hour) |>
  mutate(seq = rep(c(1, 2, 3, 4), 100)) |>
  mutate(triplicate = case_when(
    site_id == "CN10" ~ seq == 4,
    site_id == "CN11" ~ seq == 1,
    site_id == "CN31" ~ seq == 3,
    site_id == "CN41" ~ seq == 2
  )) |>
  cross_join(tibble(replicate = c("A", "B", "C", "FIELD BLANK"))) |>
  filter(triplicate | (!triplicate & replicate == "A")) |>

  mutate(label_date = format(date, "%a %d %b"),
         label_hour = str_c(hour, ": ____"),
         label_site = str_c(site_id),
         label_replicate = replicate)
  
  # Write csv
  write_csv(labels, "../../../Infinity/Infinity Projects - Files/190-56 Coastal WQ/09_Sample Preparation/bottle_labels.csv")
  
# Prepare data for mail merge
  labels |>
    select(label_date, label_site, label_replicate, label_hour, hour, date) |>
    mutate(label_hour = str_remove_all(label_hour, "_")) |>
    pivot_wider(id_cols = c(label_date, label_site, hour, date), names_from = label_replicate, values_from = label_hour) |>
    write_csv("../../../Infinity/Infinity Projects - Files/190-56 Coastal WQ/09_Sample Preparation/Camps Bay High-Frequency Sampling/mail_merge.csv")
```
