---
title: "historical_coastal_water_quality"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r message = FALSE}
library(tidyverse)
library(dbplyr)
library(DBI)
library(pdftools)
library(readxl)
```

```{r db connection}
# Enter credentials when prompted
con <- dbConnect(RPostgres::Postgres(),
  host = "aws-0-eu-central-1.pooler.supabase.com",
  port = 5432,
  user = str_c(rstudioapi::askForPassword(prompt = "Username: "), "wnrvdvesovnkmqbhkhjz", sep = "."),
  password = rstudioapi::askForPassword(),
  dbname = "postgres"
)
```

```{r prepare-city-colours}
city_blue <- "#0098c5"
city_green <- "#bacf00"
city_pink <- "#c8006f"
city_teal <- "#005870"
city_dark_green <- "#446414"
city_red <- "#9d2235"
city_brown <- "#47292e"
city_tan <- "#98871f"
```

```{r}
dbGetInfo(con)
```

```{r data-import}
results <- tbl(con, I("coastal.results_view")) |> collect()
```

# Analysis of effect of daily samples on water quality category

```{r categories-including-dailies}
results |>
  filter(site_id %in% c("CN04", "CN41", "CN11", "XCS34", "XCS26")) |>
  filter(sample_date > date(now()) - years(1)) |>
  arrange(desc(sample_date)) |>
  group_by(site_id) |>
  summarise(number_of_samples = n(), min_value = min(numeric_value), max_value = max(value), hazen90 = quantile())

```

