---
title: "Triplicate Sampling Analysis"
author: "Francois van Schalkwyk"
date: "2025-07-12"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

## Loading packages

```{r load-packages, echo = FALSE}
library(tidyverse)
library(dbplyr)
library(DBI)
library(extrafont)
```

## Database Connection

```{r db-connection}
# Connect to the Postgres database
# Enter credentials when prompted
con <- dbConnect(RPostgres::Postgres(),
  host = "aws-0-eu-central-1.pooler.supabase.com",
  port = 5432,
  user = str_c(rstudioapi::askForPassword(prompt = "Username: "), "wnrvdvesovnkmqbhkhjz", sep = "."),
  password = rstudioapi::askForPassword(),
  dbname = "postgres"
)
DBI::dbGetInfo(con)
```

# Analysis

```{r import-data}
triplicates <- tbl(con, I("coastal.triplicate_results")) |>
  select(-result_id) |>
  arrange(sample_date, lab_code, sample_id) |>
  mutate(sample_type = case_when(
    str_sub(sample_id, 1, 2) == "FB" ~ "field control",
    str_sub(sample_id, 1, 2) == "LB" ~ "lab control",
    .default = "field sample"
  )) |>
  collect()

sites <- tbl(con, I("coastal.sites_view")) |>
  collect()

df <- sites |>
  inner_join(triplicates, by = "site_id")
```

```{r data-check}
# Overview of the data
df
head(df)
summary(df)
```

How do the results compare between labs?

```{r, fig.height = 11, fig.width = 8.7, dpi = 600}
fig1 <- df |>
  select(site_id, site_description, long, lat, sample_date, lab_code, sample_type, enterococci_cfu_per_100ml) |>
  group_by(site_description, sample_date, lab_code, sample_type) |>
  rename(censored_value = enterococci_cfu_per_100ml) |>
  mutate(numeric_value = if_else(censored_value %in% c("ND", "<1"), 0, censored_value |> as.numeric())) |>
  mutate(sample_type = str_to_title(sample_type) |> fct(levels = c("Field Sample", "Field Control", "Lab Control"))) |>
  summarise(mean = mean(numeric_value), sd = sd(numeric_value)) |>
  # mutate(mean = if_else(sample_type %in% c("Field Control", "Lab Control") & mean == 0, 1, mean)) |>
  ggplot(aes(x = fct(lab_code), y = mean, ymin = mean - sd, ymax = mean + sd, fill = sample_type)) +
  labs(y = expression("Mean (±SD) enterococci (cfu per 100 mL)")) +
  geom_errorbar(position = position_dodge(preserve = "single", width = 1), width = 0.3) +
  geom_col(position = position_dodge(preserve = "single", width = 1)) +
  facet_wrap(~str_c(sample_date, site_description, sep = "\n"), ncol = 3, scales = "free") +
  scale_fill_brewer(name = "Sample Type", type = "qual", palette = 3) +
  theme(
    axis.title.x = element_blank(),
    legend.position = "bottom",
    text = element_text(family = "Century Gothic")
  )

ggsave(filename = "triplicate_results.jpg", plot = fig1, path = "02 Output Data/", width = 8.7, height = 11, dpi = 600)

# Export the data
df |>
  select(-site_order, -category, -coastline, -active) |>
  arrange(sample_date, lab_code, sample_type) |>
  write_csv("02 Output Data/triplicate_sampling_results.csv")
```

```{r plot-linegraph, fig.width = 8.7, fig.height = }

```

